module.exports = {
    'https://able-group-dev.d-velop.cloud': {
        host: 'https://able-group-dev.d-velop.cloud',
        repoId: '1a2cde3f-2913-3dc2-4a2e-e623459ac23a',
        customerCategory: 'ADEB',
        customerNumberProperty: '81',
        debitorIdProperty: '47',
        partnerNameProperty: '80',
        partnerIdProperty: '32',
        partnerRoleProperty: '33',
        customerDocumentTypeId: '130',
        contractNameProperty: '17',
        contractStartdateProperty: '28',
        contractEnddateProperty: '29',
        contractTypeProperty: '130',
        folderMimeType: 'application/vnd.dvelop.folder',
        customerRegisterCaption: '02 - Kunde Rahmenvereinbarungen',
        aueProperty: '213',
        dvProperty: '214',
        wvProperty: '215',
        pvProperty: '216',
        internalCustomerContractNumberProperty: '15',
        internalCaseNumberProperty: '39',
        regEx: 'D[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]',
    },
    'https://able-group-qas.d-velop.cloud': {
        host: 'https://able-group-qas.d-velop.cloud',
        repoId: '64bdf712-b328-5f46-8fd0-b8e67aaf8bec',
        customerCategory: 'ADEB',
        customerNumberProperty: '138',
        debitorIdProperty: '34',
        partnerNameProperty: '139',
        partnerIdProperty: '25',
        partnerRoleProperty: '41',
        customerDocumentTypeId: '169',
        contractNameProperty: '8',
        contractStartdateProperty: '21',
        contractEnddateProperty: '22',
        contractTypeProperty: '169',
        folderMimeType: 'application/vnd.dvelop.folder',
        customerRegisterCaption: '02 - Kunde Rahmenvereinbarungen',
        aueProperty: '222',
        dvProperty: '223',
        wvProperty: '224',
        pvProperty: '225',
        internalCustomerContractNumberProperty: '6',
        internalCaseNumberProperty: '83',
        regEx: 'Q[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]',
    },
    'https://able-group-version.d-velop.cloud': {
        host: 'https://able-group-version.d-velop.cloud',
        repoId: '576583f0-8cd0-5796-bc94-e49426e7bbfb',
        customerCategory: 'ADEB',
        customerNumberProperty: '132',
        debitorIdProperty: '34',
        partnerNameProperty: '133',
        partnerIdProperty: '25',
        partnerRoleProperty: '41',
        customerDocumentTypeId: '163',
        contractNameProperty: '8',
        contractStartdateProperty: '21',
        contractEnddateProperty: '22',
        contractTypeProperty: '163',
        folderMimeType: 'application/vnd.dvelop.folder',
        customerRegisterCaption: '02 - Kunde Rahmenvereinbarungen',
        aueProperty: '215',
        dvProperty: '216',
        wvProperty: '217',
        pvProperty: '218',
        internalCustomerContractNumberProperty: '6',
        internalCaseNumberProperty: '84',
        regEx: 'P[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]',
    },
    'https://able-group.d-velop.cloud': {
        host: 'https://able-group.d-velop.cloud',
        repoId: '16d943a8-4683-5ffb-b564-f3bf1903a967',
        customerCategory: 'ADEB',
        customerNumberProperty: '132',
        debitorIdProperty: '34',
        partnerNameProperty: '133',
        partnerIdProperty: '25',
        partnerRoleProperty: '41',
        customerDocumentTypeId: '163',
        contractNameProperty: '8',
        contractStartdateProperty: '21',
        contractEnddateProperty: '22',
        contractTypeProperty: '163',
        folderMimeType: 'application/vnd.dvelop.folder',
        customerRegisterCaption: '02 - Kunde Rahmenvereinbarungen',
        aueProperty: '215',
        dvProperty: '216',
        wvProperty: '217',
        pvProperty: '218',
        internalCustomerContractNumberProperty: '6',
        internalCaseNumberProperty: '84',
        regEx: 'P[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]',
    },
};
